baseURL: "https://www.bruxodasilva.xyz/"
languageCode: en-us
title: Diogo Ferreira
paginate: 3
theme: PaperMod

enableRobotsTXT: true
enableEmoji: true

googleAnalytics: G-1J7F1B9V5W

params:
  env: production
  title: Diogo Ferreira
  description: "Diogo Ferreira Personal Page & Blog"
  keywords: [Blog, Portfolio, Personal Page]
  author: Diogo Ferreira
  
  ShowReadingTime: true

  homeInfoParams:
    Title: Diogo Ferreira
    Content: Welcome to my little corner in the web

  profileMode:
    enabled: true
    title: "Diogo Ferreira" # optional default will be site title
    subtitle: "CTO, Founder, Entrepreneur"
    subtitle2: "Proudly from Porto, Portugal"
    imageUrl: "/img/me.png"
    imageTitle: "Diogo Ferreira" # optional
    imageWidth: 200 # custom size
    imageHeight: 200 # custom size
    buttons:
      - name: About Me
        url: "/about/"
      - name: Blog
        url: "/blog/"

  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/ferreiradiogo/"
    - name: twitter
      url: "https://twitter.com/bruxo_da_silva"
    - name: github
      url: "https://github.com/bruxodasilva"

menu:
  main:
    - identifier: about
      name: About Me
      url: /about/
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 50
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30

# markup:
#   goldmark:
#     renderer:
#       unsafe: true